const { Octokit } = require('@octokit/rest');

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

const owner = process.env.GITHUB_OWNER;
const repo = process.env.GITHUB_REPO;

async function getMainBranchSHA() {
  const { data } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: 'heads/main'
  });
  return data.object.sha;
}

async function createBranch(branchName, sha) {
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha
  });
}

async function commitFile(branchName, filename, content, message) {
  let fileSHA = null;

  try {
    const { data } = await octokit.rest.repos.getContent({
      owner,
      repo,
      path: filename,
      ref: branchName
    });
    fileSHA = data.sha;
  } catch (e) {
    fileSHA = null;
  }

  await octokit.rest.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: filename,
    message,
    content: Buffer.from(content).toString('base64'),
    branch: branchName,
    ...(fileSHA && { sha: fileSHA })
  });
}

async function createPullRequest(branchName, title, body) {
  const { data } = await octokit.rest.pulls.create({
    owner,
    repo,
    title,
    body,
    head: branchName,
    base: 'main'
  });
  return data.html_url;
}

async function generatePRDescription(prompt, code, attempts, language) {
  return `## AI Generated Code

**Task:** ${prompt}
**Language:** ${language}
**Attempts needed:** ${attempts.length}
**Quality:** Code passed all checks ✅

## Generated Code

\`\`\`${language}
${code}
\`\`\`

## How it was generated

This code was automatically generated and self-corrected by the Self-Correcting AI Assistant.
${attempts.length > 1 ? `The AI needed ${attempts.length} attempts to produce working code.` : 'The AI produced working code on the first attempt.'}

---
*Auto-generated by Self-Correcting AI*`;
}

async function createCodePR(prompt, code, language, attempts) {
  const timestamp = Date.now();
  const branchName = `ai-fix/${language}-${timestamp}`;
  const filename = `generated/${language}/solution_${timestamp}.${getExtension(language)}`;

  const sha = await getMainBranchSHA();
  await createBranch(branchName, sha);

  const commitMessage = `feat: AI generated ${language} solution for "${prompt.slice(0, 50)}"`;
  await commitFile(branchName, filename, code, commitMessage);

  const prTitle = `AI Solution: ${prompt.slice(0, 60)}`;
  const prBody = await generatePRDescription(prompt, code, attempts, language);
  const prUrl = await createPullRequest(branchName, prTitle, prBody);

  return { branchName, filename, prUrl };
}

function getExtension(language) {
  const map = { python: 'py', java: 'java', cpp: 'cpp' };
  return map[language] || 'txt';
}

module.exports = { createCodePR };